config/routes.rb
Rails.application.routes.draw do
  
  get 'favorites/create'
  get 'favorites/destroy'
  get 'relationships/create'
  get 'relationships/destroy'
  get 'microposts/create'
  get 'microposts/destroy'
  root to: "toppages#index"

  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"

  get "signup", to: "users#new"
  resources :users do
    member do
      get :following
      get :follower
    end  
  end
   
  resources :microposts do
   resources :comments, only: [:create]
  end 

  resources :favorites, only: [:create, :destroy]

  resources :relationships, only:[:create, :destroy] 
   
end

app/models/user.rb
 class User < ApplicationRecord
	before_save { self.email.downcase! }
	validates :lastname, presence: true, length: { maximum: 10 }
	validates :firstname, presence: true, length: { maximum: 10 }
	validates :username, presence: true, length: { maximum: 20 },
						uniqueness: { case_sensitive: false }
	validates :email, presence: true, length: { maximum: 255 },
						format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
						uniqueness: { case_sensitive: false }
	validates :introduction, length: { maximum: 100 }
	has_secure_password
	validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
	has_many :microposts, dependent: :destroy
	has_many :comments, dependent: :delete_all
	has_many :relationships, dependent: :delete_all
	has_many :followings, through: :relationships, source: :follow
	has_many :reverse_of_relationship, class_name: "Relationship", foreign_key: "follow_id"
	has_many :followers, through: :reverse_of_relationship, source: :user
	has_many :favorites, dependent: :destroy
	
	def follow(other_user)
		unless self == other_user
			self.relationships.find_or_create_by(follow_id: other_user.id)
		end
	end

	def unfollow(other_user)
		relationship = self.relationships.find_by(follow_id: other_user.id)
		relationship.destroy if relationship
	end

	def following?(other_user)
		self.followings.include?(other_user)
	end
	
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_logged_in, only: [:index, :edit, :update, :destroy, :folloeing, :followers]
  before_action :correct_user, only: [:edit, :update, :destroy]
  
  def new
    @user = User.new
  end

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id]) 
    @microposts = @user.microposts 
    @micropost = Micropost.new  
    @comments = @micropost.comments  
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:sucesee]= "登録が完了しました"
      login @user
      redirect_to @user
    else
      render "new"
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "プロフィールを更新しました。"
      redirect_to @user
    else
      render "edit"
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "アカウントを削除しました。"
    redirect_to root_url
  end

  def following
    @title = "Following"
    @user = User.find(params[:id])
    @users = @user.followings
    render 'show_follow'
  end 

  def follower
    @title = "Followers"
    @user = User.find(params[:id])
    @users = @user.followers
    render 'show_follower'
  end 

  private

  def user_params
    params.require(:user).permit(:lastname, :firstname, :username, :email, :tel, :introduction, :password, :password_confirmation)
  end

end

app/helpers/users_helper.rb
module UsersHelper
	def gravatar_url(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
		"https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
	end
end

app/views/users/_form.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
		<%= form_with(model: @user, local: true) do |f| %>
			<%= render 'shared/error_messages' %>
				<div>
					<%= f.label :lastname, "性" %>
					<%= f.text_field :lastname, class: 'form-control' %>	
				</div>
				<div>
					<%= f.label :firstname, "名" %>
					<%= f.text_field :firstname, class: 'form-control' %>		
				</div>
				<div>
					<%= f.label :username, "ユーザーネーム" %>
					<%= f.text_field :username, class: 'form-control' %>	
				</div>
				<div>
					<%= f.label :tel, "電話番号" %>
					<%= f.text_field :tel, class: 'form-control' %>	
				</div>
				<div>
					<%= f.label :email, "メールアドレス" %>
					<%= f.text_field :email, class: 'form-control' %>	
				</div>
				<div>
					<%= f.label :introduction, "自己紹介" %>
					<%= f.text_field :introduction, class: 'form-control' %>	
				</div>
				<div>
					<%= f.label :password, "パスワード" %>
					<%= f.password_field :password, class: 'form-control' %>
				</div>
				<div>
					<%= f.label :password_confirmation, "パスワード(確認用)" %>
					<%= f.password_field :password_confirmation, class: 'form-control' %>
				</div>
				<%= f.submit yield(:button_text), class: "btn btn-primary" %>
		<% end %>  
	</div>
</div>	

app/views/users/edit.html.erb
<% provide(:button_text, "編集する")%>
  <h1>プロフィール編集</h1>
		<div>
			<%= render "form" %>
		</div>

app/views/users/new.html.erb
<% provide(:title, '新規登録') %>
<% provide(:button_text, '新規登録') %>

<h1>新規登録</h1>
  <div>
		<%= render "form" %>
	</div>

app/views/users/show.html.erb
<% provide(:title, "ユーザー詳細") %>
  <!--ユーザープロフィール-->
  <div class="container">
    <div class="row">
      <aside class="col-md-6">
        <section class="user_info">
          <h1>
            <img class="rounded img-fluid" src="<%= gravatar_url(@user, { size: 80 }) %>" alt="">
            <%= @user.username %>
          </h1>
          <div>
            <%= @user.introduction %>
          </div>     
            <% if @user == current_user %>
              <%= link_to "プロフィール編集", edit_user_path(current_user) %>
              <%= link_to "アカウント削除", user_path, method: :delete, data: { confirm: "アカウントを削除しますか?" }%>
            <% end %> 
        </section>
      </aside>
    </div>
  </div> 

  <!--フォローボタン-->
  <%= render 'relationships/follow_button', user: @user %>
  <div class="container">
    <ul class="f-container nav nav-tabs nav-justified mb-3">
      <li class="col-md-5 nav-item"><a href="<%= following_user_path(@user) %>">フォロー</a><%= @count_followings %></li>
      <li class="col-md-5 nav-item"><a href="<%= follower_user_path(@user) %>">フォロワー</a><%= @count_followers %></li>
    </ul>
  </div>

  <!--投稿写真一覧-->
  <% if @user.microposts.any? %>
    <p>投稿数（<%= @user.microposts.count %>）</p>
      <div class="f-container">
        <% @microposts.each do |micropost| %> 
          <div class="justify-content-start col-md-4">
            <%= link_to ( image_tag ( micropost.picture.url if micropost.picture)), micropost %>
          </div>
        <% end %> 
      </div>
  <% end %>
 

app/views/users/show_follow.html.erb
<% provide(:title, @title) %>
	<!--フォロー一覧-->
	<h3><%= @title %></h3>
		<% if @users.any? %>
			<% @user.followings.each do |user| %>
				<img class="rounded img-fluid" src="<%= gravatar_url(user, { size: 30 }) %>" alt="">
				<%= user.username %>
				<%= link_to '詳細', user_path(user) %>
			<% end %>
		<% end %>
		

app/views/users/show_follower.html.erb
<% provide(:title, @title) %>
	<!--フォロワー一覧-->
	<h3><%= @title %></h3>
		<% if @users.any? %>
			<% @user.followers.each do |user| %>
				<img class="rounded img-fluid" src="<%= gravatar_url(user, { size: 30 }) %>" alt="">
				<%= user.username %>
				<%= link_to '詳細', user_path(user) %>
			<% end %>
		<% end %>