config/routes.rb
Rails.application.routes.draw do
  
  get 'favorites/create'
  get 'favorites/destroy'
  get 'relationships/create'
  get 'relationships/destroy'
  get 'microposts/create'
  get 'microposts/destroy'
  root to: "toppages#index"

  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"

  get "signup", to: "users#new"
  resources :users do
    member do
      get :following
      get :follower
    end  
  end
   
  resources :microposts do
   resources :comments, only: [:create]
  end 

  resources :favorites, only: [:create, :destroy]

  resources :relationships, only:[:create, :destroy] 
   
end

app/views/layouts/_header.html.erb
<header class= "navbar navbar-fixed-top navber-inverse">
　<div class="container">
		<nav>
			<% if logged_in? %>
				<ul class="nav navbar-nav navbar-right">
					<li class="nav-item"><%= link_to "TOP", root_path %></li>
					<li class="nav-item"><%= link_to "SEARCH", microposts_path %></li>
					<li class="nav-item"><%= link_to "MYPAGE", current_user %></li>
					<li class="nav-item"><%= link_to "UPROAD", new_micropost_path  %></li>
					<li class="nav-item"><%= link_to "Logout", logout_path, method: :delete %></li>
				</ul>
			<% else %>
				<ul class="nav navbar-nav navbar-right">
					<li class="nav-item"><%= link_to "TOP", root_path %></li>
					<li class="nav-item"><%= link_to "SEARCH", microposts_path %></li>
					<li class="nav-item"> <%= link_to "MYPAGE", current_user %></li>
					<li class="nav-item"><%= link_to "UPROAD", new_micropost_path %></li>
				</ul>
			<% end %>
		</nav>	
	</div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<html lang="ja">
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title><%= (yield(:title)) %>InstaApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" rel="stylesheet">
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
   <![endif]-->
  </head>
  <body>
    <div class="container">
      <%= render "layouts/header" %>
      <%= render "shared/flash_messages.html" %>
      <%= yield %>
    </div>  
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  </body>
</html>